### ISSUE TITLE
How set withCredentials in global configuration?

### ISSUE THREAD

**Issue by skushnerchuk** [RobertoLangarica/quasar-app-extension-api-wrapper#2]
Not to do this in every request?

**Comment by RobertoLangarica** [comment]
Hi, thanks for using the extension.

Here is the link to the readme section that you need:
[https://github.com/RobertoLangarica/quasar-app-extension-api-wrapper#global-configuration](url)

Look for the: setAuthorization function, you can set this in your App.vue (when the app starts) or after a login to service.

Note: You can still providing a different authorization for each request.
